include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    todo: ignore

linter:
  rules:
    # Code style
    prefer_single_quotes: true
    always_use_package_imports: true

    # Clean code
    avoid_print: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true

    # Null safety & safety
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true

    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Readability
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
